### ISSUE TITLE
Does log file size is fixed?  

### ISSUE THREAD

**Issue by darongE** [iamantony/qtcsv#14]
I'm making log file.  I want to make fixed size.
Does file size is fixed?
e.g ) 1MB = 1024kb

**Comment by iamantony** [comment]
qtcsv do not set any constraints on the size of the csv-file. If you want to create csv-file of fixed size, you  will need to manually control the amount of data that you want to write to file. But this is hard way, because you'll need to take into account that the result file will contain additional characters like  separator symbols and line ending symbols.

Maybe for you it will be easier to write all data in one file and than split it into several 1MB-files?
For example, using [split command in Linux](http://stackoverflow.com/questions/2016894/easy-way-to-split-a-large-text-file).
