### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by oya163** [iamantony/qtcsv#19]
I am not able to install this library. I am using Windows operating system.
I get error like this

```
C:\Users\cvpr\Documents\QT\qtcsv-master>make
cd src/ && ( test -e Makefile || C:/Qt/5.6/mingw49_32/bin/qmake.exe C:/Users/cvpr/Documents/QT/qtcsv-master/src/src.pro -o Makefile ) && make -f Makefile
make[1]: Entering directory `C:/Users/cvpr/Documents/QT/qtcsv-master/src'
C:/Program Files (x86)/GnuWin32/bin/make -f Makefile.Release
/usr/bin/sh: -c: line 0: syntax error near unexpected token `('
/usr/bin/sh: -c: line 0: `C:/Program Files (x86)/GnuWin32/bin/make -f Makefile.Release'
make[1]: *** [release] Error 1
make[1]: Leaving directory `C:/Users/cvpr/Documents/QT/qtcsv-master/src'
make: *** [sub-src-make_first] Error 2
```

**Comment by iamantony** [comment]
Hi! I think the reason why you have such an error is _GnuWin32_. First of all check that your PATH variable contains path to _GnuWin32/bin_. Also the root of the problem could be the installation path of GnuWin32, because it contains space character in _"Program Files (x86)"_. Try to install GnuWin32 into path without space characters (like C:\\GnuWin32).

Or if you do not obliged to use GnuWin32, try to build qtcsv with _MinGW_ (this is preferred way). I think you are already have it on your computer because you have installed Qt 5.6. Check out path _C:\Qt\Tools\mingw492_32/bin_. It should contain _make_ binary. Add this path to PATH and try to build library.
